
services:
  my-redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  my-mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: goal
    ports:
      - "3306:3306"
