version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
